### ISSUE TITLE
As a user, I would like to use the operating system of my choice.

### ISSUE THREAD

**Issue by noncog** [noncog/open-cycle-time#1]
### Acceptance Criteria
- [x] Scenario: Using Linux
When I use the software:
  - [x] Then the system builds and installs all possible dependencies.
  - [x] And all features work.
- [x] Scenario: Using macOS
When I use the software:
  - [x] Then the system builds and installs all possible dependencies.
  - [x] And all features work.
- [x] Scenario: Using Windows
When I use the software:
  - [x] Then the system builds and installs all possible dependencies.
  - [x] And all features work.

### Tasks
- [x] Prove system compatibility using continuous integration.
- [x] Prove system compatibility using manual testing.

### Resources
- None.

### Notes
- None.
