### ISSUE TITLE
As a user, I would like simple instructions for installing and using the software.

### ISSUE THREAD

**Issue by noncog** [noncog/open-cycle-time#11]
### Acceptance Criteria
- [ ] Scenario: When attempting to understand the software
After accessing the repository:
  - [ ] Then I can access installation instructions.
  - [ ] And I can access usage instructions.

### Tasks
- [ ] Example.

### Resources
- None.

### Notes
- None.
