### ISSUE TITLE
As a user, I would like to use the compiler of my choice.

### ISSUE THREAD

**Issue by noncog** [noncog/open-cycle-time#2]
### Acceptance Criteria
- [x] Scenario: Using Linux
When I use the software:
  - [x] Then the system compiles using a major compiler.
  - [x] And all features work.
- [x] Scenario: Using macOS
When I use the software:
  - [x] Then the system compiles using a major compiler.
  - [x] And all features work.
- [x] Scenario: Using Windows
When I use the software:
  - [x] Then the system compiles using a major compiler.
  - [x] And all features work.

### Tasks
- [x] Prove compiler compatibility using continuous integration.
- [x] Prove compiler compatibility using manual testing.

### Resources
- None.

### Notes
- None.
