### ISSUE TITLE
As a user, I would like the freedom to use the software for profit.

### ISSUE THREAD

**Issue by noncog** [noncog/open-cycle-time#3]
### Acceptance Criteria
- [x] Scenario: Using the software for business purposes
When using the results:
  - [x] Then I can legally use the analysis for commercial gain.

### Tasks
- [x] Add an open and permissive license to the repository.

### Resources
- None.

### Notes
- None.

**Comment by noncog** [comment]
Closed by #28
