### ISSUE TITLE
As a user, I would like the source code to audit, understand, and extend the software.

### ISSUE THREAD

**Issue by noncog** [noncog/open-cycle-time#4]
### Acceptance Criteria
- [x] Scenario: When downloading the software
After the build system has completed:
  - [x] Then the system contains all the source code for all libraries used.

### Tasks
- [x] Ensure the use of only open source libraries.
- [x] Ensure all dependencies and code are built from source.

### Resources
- None.

### Notes
- None.
