### ISSUE TITLE
As a user, I want the software to not require a dedicated graphics card.

### ISSUE THREAD

**Issue by noncog** [noncog/open-cycle-time#5]
### Acceptance Criteria
- [x] Scenario: Using a machine without a dedicated graphics card
When I use the software:
  - [x] Then the analysis is conducted using the CPU instead of the GPU.

### Tasks
- [x] Ensure OpenCV uses the CPU instead of the GPU.
- [x] Ensure all graphics related libraries do not require a graphics card.

### Resources
- None.

### Notes
- None.
