### ISSUE TITLE
As a user, I would like to select video files using a file dialogue.

### ISSUE THREAD

**Issue by noncog** [noncog/open-cycle-time#6]
### Acceptance Criteria
- [x] Scenario: Using Linux
When selecting a video file:
  - [x] Then I can navigate to the directory the video is stored in.
  - [x] And select the video file.
- [x] Scenario: Using macOS
When selecting a video file:
  - [x] Then I can navigate to the directory the video is stored in.
  - [x] And select the video file.
- [x] Scenario: Using Windows
When selecting a video file:
  - [x] Then I can navigate to the directory the video is stored in.
  - [x] And select the video file.

### Tasks
- [x] Implement a cross-platform file dialogue.

### Resources
- None.

### Notes
- None.
