### ISSUE TITLE
As a user, I would like to accurately calculate cycle times based on video frames.

### ISSUE THREAD

**Issue by noncog** [noncog/open-cycle-time#7]
### Acceptance Criteria
- [x] Scenario: When testing a known sample
When I use the software:
  - [x] Then the calculated results are within 5% of a known manual measurement.
  
### Tasks
- [x] Add a sample video file.
- [x] Manually analyze the video file and codify the results.
- [x] Create a test comparing the results of analysis between automated and manual analysis.

### Resources
- None.

### Notes
- None.
