### ISSUE TITLE
As a user,  I want to export the results of the analysis for external use.

### ISSUE THREAD

**Issue by noncog** [noncog/open-cycle-time#8]
### Acceptance Criteria
- [x] Scenario: When using the software
After completing the analysis:
  - [x] Then I can export the results to a data file.

### Tasks
- [x] Add a button that exports the results to a data file.

### Resources
- None.

### Notes
- None.
